# Run on all files:   pre-commit run --all-files

repos:
  - repo: https://github.com/rbubley/mirrors-prettier
    rev: v3.9.4
    hooks:
      - id: prettier

  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.30
    hooks:
      - id: helmlint
