name: CI

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v7
      - uses: j178/prek-action@v3.0.0

  test:
    runs-on: ubuntu-24.04
    timeout-minutes: 15

    env:
      GITHUB_REPOSITORY: ${{ github.repository }}
      GITHUB_REVISION: ${{ github.sha }}

    steps:
      - uses: actions/checkout@v7

      # https://github.com/jupyterhub/action-k3s-helm/
      - uses: jupyterhub/action-k3s-helm@v4
        with:
          k3s-channel: v1.36

      - name: Install deployment
        run: helm upgrade --install ro-crate-validator ./chart --values ci/test-values.yaml --wait

      - name: Run helm test
        # This only checks the service is responsive, it doesn't check it's correct
        run: helm test ro-crate-validator --timeout=70s

      - name: Run 5s validation test
        run: python -munittest ci/test.py

      - name: Get logs, including on failure
        if: always()
        run: |
          for deploy in ro-crate-validator ro-crate-validator-celery ro-crate-validator-redis; do
            echo "::group::$deploy"
            kubectl logs deploy/$deploy
            echo "::endgroup::"
          done

          echo "::group::ro-crate-validator-test-validator"
          kubectl logs ro-crate-validator-test-validator
          echo "::endgroup::"

  publish-chart:
    runs-on: ubuntu-24.04
    needs:
      - lint
      - test
    permissions:
      # Requires write permission to push to the GitHub Pages branch
      contents: write
    env:
      COMMIT_USER: helm-chart-bot

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Update Chart.yaml version with tag
        run: |
          export VERSION=${{ github.ref_name }}
          yq --inplace '.version = env(VERSION)' chart/Chart.yaml
          git diff

      - name: Publish to gh-pages
        uses: manics/helm-gh-pages-action@v0.1.1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          chart-dir: chart
